feat: add support for Chrome Beta
dhruvmanila/telescope-bookmarks.nvim pull request #10
Opened 2022-02-14 12:29 UTC by sanchay9

I know there should be a better way to do this?

2022-02-14 17:00 UTC, dhruvmanila requested changes
> I know there should be a better way to do this?

Well, right now this is the only way lol 😉 

A few small changes and this will be good to go.

2022-02-14 17:00 UTC, dhruvmanila commented on lua/telescope/_extensions/bookmarks/chrome_beta.lua
> +---NOTE: Brave and Google Chrome uses the same underlying format to store bookmarks.
```suggestion
---Collect all the bookmarks for Google Chrome Beta.
```

2022-02-14 17:00 UTC, dhruvmanila commented on lua/telescope/_extensions/bookmarks.lua
> +  chrome_beta = "Chrome",
```suggestion
  chrome_beta = "Chrome (beta)",
```

2022-02-15 06:51 UTC, sanchay9 commented on lua/telescope/_extensions/bookmarks.lua
> +  chrome_beta = "Chrome",
I think I would prefer the prompt title to be just Chrome 😄
![2022-02-15_12-08](https://user-images.githubusercontent.com/53908642/154007787-099d3570-9080-4ed9-bf0f-dba0c0f3fc74.png)

2022-02-17 06:00 UTC, dhruvmanila approved these changes

2022-02-17 06:00 UTC, merged

2022-02-17 06:01 UTC, dhruvmanila commented
Thanks!